# Generated by Django 5.2.14 on 2026-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producto_descripcion_corta_producto_destacado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='almacenamiento_descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='beneficios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='diseno',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='memoria_ram_descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='pantalla',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='procesador_descripcion',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='producto',
            name='serie',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
