# Generated by Django 5.2.14 on 2026-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='procesador',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
